## mysql
spring:
  datasource:
    url: jdbc:mysql://47.111.190.233:3306/teach?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: songjiazhen.123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
# 输出sql
logging:
  level:
    com.song.mapper: debug
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:com/song/mapper/xml/*.xml
  type-aliases-package: com.song.pojo
    